This check in is a major refractor of the way System preferences are done. It contains
+ Lots of code clean up & added convenience methods to SystemMemory

+ Now all user preferences are supplied to bash / bat  via 
"IdvCommandLinePrefs". (I still have to do the MS bat work)

+ IdvCommandLinePrefs takes into account a -userpath command line arg. (I could not detect an internal IDV API that could obtain this information without instantiating the whole IDV.) There are still bugs here. Will be fixing shortly.

diff --git a/ucar/unidata/idv/release/installer/runIDVNew b/ucar/unidata/idv/release/installer/runIDVNew
--- a/ucar/unidata/idv/release/installer/runIDVNew
+++ b/ucar/unidata/idv/release/installer/runIDVNew
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+##Error message, if needed.
+error_msg="IDV failed to start. Please contact support-idv@unidata.ucar.edu"
+
 java="java"
 if test -f jre/bin/java; then
 ##We are in the installer directory
@@ -19,7 +22,20 @@ else
     fi
 fi
 
-heap="$(${java} -cp idv.jar ucar.unidata.idv.UserMemory  2>&1 )"
+prefs="$(${java} -client -cp idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1 )"
+
+if [ $? -eq 1 ]; then
+    echo "IDV failed to start. Please contact support-idv@unidata.ucar.edu"
+    exit 1
+fi    
+
+eval "${prefs}"
+
+##Sanity check. If memory variable does not exist, we have problems
+if test -z ${idv_memory}; then
+    echo "IDV failed to start. Please contact support-idv@unidata.ucar.edu"
+    exit 1
+fi
 
 dirname=`dirname $0`
-${java} -Xmx${heap}m -Didv.enableStereo=false -jar ${dirname}/idv.jar
+${java} -Xmx${idv_memory}m -Didv.enableStereo=false -jar ${dirname}/idv.jar $*
